### ISSUE TITLE
Awesome 3D tanks

### ISSUE THREAD

**Issue by chase-moskal** [ChaseMoskal/Nanoshooter#11]
Let's have a cool variety of stylish tanks. No rules man.

If we want to go futuristic, maybe we should consider robotic tanks without drivers, too – drone tanks?
### Tanks are cool:
- Each tank in its own `.blend` file.
  - Each tank should be in its own folder, inside a folder called `/art/tanks/`.. this doesn't exist at time of writing, but I'll soon update the art structure this way.
- Tank must be comprised of two separate objects:
  - `Turret` – Top of the tank. My loading system looks for that name and initializes it as the swivel part.
  - `Chassis` – Body of the tank, with the treads and everything below the turret.
- Both objects (Chassis & Turret) must share the same single material.
  - Material can have textures assigned, color map, spec map, normal map.
    - I'm still not sure whether Babylon wants an RGB normal map or a simple black and white bump map.. maybe let's try it both ways..
- Keep all assets unpacked/external from the `.blend` file – just keep all textures and related photoshop documents in the tank's folder.
- Export `.obj` in the tank's own folder, alongside the `.blend`.

_Make it pretty!_

**Comment by lonnie-ralfs** [comment]
Could maybe have a commander tank? Idea would be place your commander at your base? Maybe give a set range?! Then he would need to find better hiding spots OOooo! Airdrop a small, fast, weaker tank he controls (drone/rover style). Killing the weak commander would stop all drone tanks he controls.

**Comment by lonnie-ralfs** [comment]
I think for now though I'm going to focus on getting the 2 I have designed game ready just so we have something.

**Comment by chase-moskal** [comment]
@Loonietoon:

> Could maybe have a commander tank? [...]

I dig these ideas. I see nanoshooter naturally evolving toward RTS-style gameplay.

> I think for now though I'm going to focus on getting the 2 I have designed game ready just so we have something. []

Totally. Go ahead and work on `tank-alpha.blend` and `tank-bravo.blend` in the `/art/` directory.

In Blender, if you export to `.obj`, you can hit refresh in `index.html` and you'll be able to see your tanks in-game instantly. To do this, first you'll have to clone and build the project locally on your machine. We'll talk about this soon.

**Comment by chase-moskal** [comment]
@Loonietoon – I just deployed work for issue #14, some really cruddy tank movement via WASD.

It's a start!

**Comment by chase-moskal** [comment]
@Loonietoon — we need the cannon barrel to rotate along the vertical axis independently from the rest of the gun turret.

**Comment by chase-moskal** [comment]
Lonnie, you did it! Tank alpha and bravo accomplish this ticket.

The next step, is ticket #25.
