### ISSUE TITLE
Attack bot — comes at you

### ISSUE THREAD

**Issue by chase-moskal** [ChaseMoskal/Nanoshooter#37]
We need some kind of a robotic enemy to play against.

It should wander randomly, seeking to attack players.

**Comment by lonnie-ralfs** [comment]
![nanobotconcept2](https://cloud.githubusercontent.com/assets/19894550/17267922/b6e1ad82-55cc-11e6-9d0e-7a85de1d2957.png)

Which option!?

**Comment by chase-moskal** [comment]
Option 2 has my vote, yo.

**Comment by VSRambo** [comment]
My vote is option 2, good stuffs Lonnie now get back to work :P
