### ISSUE TITLE
Rename "Akkadian Games" to "Elamite Games"?

### ISSUE THREAD

**Issue by chase-moskal** [ChaseMoskal/Nanoshooter#53]
# [Akkadian Empire](https://en.wikipedia.org/wiki/Akkadian_Empire) / [Akkadian Language](https://en.wikipedia.org/wiki/Akkadian_language)
- Babylonia was Akkadian-speaking, literally called "Country of Akkad". 
# [Elam](https://en.wikipedia.org/wiki/Elam) / [Elamite Language](https://en.wikipedia.org/wiki/Elamite_language)
- Susa was the capital of the Elam civilization.

**Comment by chase-moskal** [comment]
Guys, help me decide our official organization name. Should we rename to _Elamite Games?_

**Comment by VSRambo** [comment]
Akkadian Games

**Comment by chase-moskal** [comment]
Won't rename. Issue closed.

_Akkadian Games_ it shall remain.
